name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: I think it could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?
      placeholder: I've also considered...

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide examples of how this feature would be used
      render: typescript
      placeholder: |
        import { api } from '@monster-codes/api-core-library';
        
        // Example of how the new feature would be used
        const result = await api.get({
          // new feature usage
        });

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to similar features in other libraries or relevant documentation
      placeholder: |
        - [Library X does something similar](https://example.com)
        - [Related RFC or discussion](https://example.com)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing
        - label: I can help with documentation
