# CI workflow for monorepo - validates all changes
# This runs on every push/PR to ensure code quality

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run all checks
        run: |
          echo "🔍 Running type check..."
          yarn type-check
          
          echo "🧪 Running tests..."
          yarn test
          
          echo "🏗️ Building packages..."
          yarn build

      - name: Check changeset status
        if: github.event_name == 'pull_request'
        run: |
          echo "📝 Checking if changesets are needed..."
          if yarn changeset status --since=origin/main 2>/dev/null; then
            echo "✅ Changesets status OK"
          else
            echo "⚠️ Consider adding a changeset if you made significant changes"
            echo "Run: yarn changeset"
          fi


