# This workflow will run tests using node and then publish a package to npm when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# 
# IMPORTANT: You need to add an NPM_TOKEN secret to your repository:
# 1. Generate an npm access token at https://www.npmjs.com/settings/tokens
# 2. Add it as a repository secret named NPM_TOKEN in GitHub Settings > Secrets and variables > Actions
#
# Alternative: To publish to GitHub Packages instead, change registry-url to:
# registry-url: 'https://npm.pkg.github.com'

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build


